### ISSUE TITLE
Dependencies for conda environments errors 

### ISSUE THREAD

**Issue by SylarZiling** [dingdingcai/OVE6D-pose#2]
Thank you for the work! I am trying to build with a conda environment but the i have some questions  from the requirenments.txt. 

for pytorch3d, in the requirements.txt files # pytorch3d==0.4.0 
in the pytorch3d github, the recommended pytorch version is PyTorch 1.4, 1.5.0, 1.5.1, 1.6.0, 1.7.0, or 1.7.1 
however, the requirements.txt has pytorch 1.8.0 and torchvision=0.9.0 

any update on the requirenments.txt with a environment.yaml file will be great. 

Best

**Comment by SylarZiling** [comment]
Another update, for preprocess_shapenet. blender python api is requried. pip install only support bpy wheels for python 3.7. need to build python api for 3.8 mannually or other methods. unkown for now.

**Comment by dingdingcai** [comment]
>  Hi, thank you for your interest! We installed Pytorch3d by the command 
"pip install "git+https://github.com/facebookresearch/pytorch3d.git"
not the one "# pytorch3d==0.4.0" which is commented. The requirement.txt is updated by removing all commented lines.

**Comment by dingdingcai** [comment]
> Thank you for the work! I am trying to build with a conda environment but the i have some questions from the requirenments.txt.
> 
> for pytorch3d, in the requirements.txt files # pytorch3d==0.4.0 in the pytorch3d github, the recommended pytorch version is PyTorch 1.4, 1.5.0, 1.5.1, 1.6.0, 1.7.0, or 1.7.1 however, the requirements.txt has pytorch 1.8.0 and torchvision=0.9.0
> 
> any update on the requirenments.txt with a environment.yaml file will be great.
> 
> Best

Hi, thank you for your interest! We installed Pytorch3d by the command
"pip install "git+https://github.com/facebookresearch/pytorch3d.git"
not the one "# pytorch3d==0.4.0" which is commented. The requirement.txt is updated by removing all commented lines.

**Comment by dingdingcai** [comment]
> 



> Another update, for preprocess_shapenet. blender python api is requried. pip install only support bpy wheels for python 3.7. need to build python api for 3.8 mannually or other methods. unkown for now.

You don't need to install bpy. Once the Blender is installed, just run the command "blender -b -p  preprocess_dataset.py" to process the data.

**Comment by SylarZiling** [comment]
> > Thank you for the work! I am trying to build with a conda environment but the i have some questions from the requirenments.txt.
> > for pytorch3d, in the requirements.txt files # pytorch3d==0.4.0 in the pytorch3d github, the recommended pytorch version is PyTorch 1.4, 1.5.0, 1.5.1, 1.6.0, 1.7.0, or 1.7.1 however, the requirements.txt has pytorch 1.8.0 and torchvision=0.9.0
> > any update on the requirenments.txt with a environment.yaml file will be great.
> > Best
> 
> Hi, thank you for your interest! We installed Pytorch3d by the command "pip install "git+https://github.com/facebookresearch/pytorch3d.git" not the one "# pytorch3d==0.4.0" which is commented. The requirement.txt is updated by removing all commented lines.

Thank you very much for the reply, I tried to install with the pip install "git+https://github.com/facebookresearch/pytorch3d.git" as well, but it failed. I could only install it through conda channel pytorch3d. However, it might cause a failure due to installed from different channel. 

BTW, I would like to ask do you have the similar exception error,

 An exception occurred in telemetry logging.Disabling telemetry to prevent further exceptions.
Traceback (most recent call last):
  File "/home/miniconda38/envs/ove6d01/lib/python3.8/site-packages/iopath/common/file_io.py", line 946, in __log_tmetry_keys
    handler.log_event()
  File "/home/miniconda38/envs/ove6d01/lib/python3.8/site-packages/iopath/common/event_logger.py", line 97, in log_event
    del self._evt
AttributeError: _evt

**Comment by dingdingcai** [comment]
Sorry, I didn't have this failure issue as well as the exception error.

**Comment by dingdingcai** [comment]
> 

Sorry, I didn't have this failure issue as well as the exception error.

**Comment by dingdingcai** [comment]
> > > Thank you for the work! I am trying to build with a conda environment but the i have some questions from the requirenments.txt.
> > > for pytorch3d, in the requirements.txt files # pytorch3d==0.4.0 in the pytorch3d github, the recommended pytorch version is PyTorch 1.4, 1.5.0, 1.5.1, 1.6.0, 1.7.0, or 1.7.1 however, the requirements.txt has pytorch 1.8.0 and torchvision=0.9.0
> > > any update on the requirenments.txt with a environment.yaml file will be great.
> > > Best
> > 
> > 
> > Hi, thank you for your interest! We installed Pytorch3d by the command "pip install "git+https://github.com/facebookresearch/pytorch3d.git" not the one "# pytorch3d==0.4.0" which is commented. The requirement.txt is updated by removing all commented lines.
> 
> Thank you very much for the reply, I tried to install with the pip install "git+https://github.com/facebookresearch/pytorch3d.git" as well, but it failed. I could only install it through conda channel pytorch3d. However, it might cause a failure due to installed from different channel.
> 
> BTW, I would like to ask do you have the similar exception error,
> 
> An exception occurred in telemetry logging.Disabling telemetry to prevent further exceptions. Traceback (most recent call last): File "/home/miniconda38/envs/ove6d01/lib/python3.8/site-packages/iopath/common/file_io.py", line 946, in __log_tmetry_keys handler.log_event() File "/home/miniconda38/envs/ove6d01/lib/python3.8/site-packages/iopath/common/event_logger.py", line 97, in log_event del self._evt AttributeError: _evt

Sorry, I didn't have this failure issue as well as the exception error.

**Comment by SylarZiling** [comment]
> > > > Thank you for the work! I am trying to build with a conda environment but the i have some questions from the requirenments.txt.
> > > > for pytorch3d, in the requirements.txt files # pytorch3d==0.4.0 in the pytorch3d github, the recommended pytorch version is PyTorch 1.4, 1.5.0, 1.5.1, 1.6.0, 1.7.0, or 1.7.1 however, the requirements.txt has pytorch 1.8.0 and torchvision=0.9.0
> > > > any update on the requirenments.txt with a environment.yaml file will be great.
> > > > Best
> > > 
> > > 
> > > Hi, thank you for your interest! We installed Pytorch3d by the command "pip install "git+https://github.com/facebookresearch/pytorch3d.git" not the one "# pytorch3d==0.4.0" which is commented. The requirement.txt is updated by removing all commented lines.
> > 
> > 
> > Thank you very much for the reply, I tried to install with the pip install "git+https://github.com/facebookresearch/pytorch3d.git" as well, but it failed. I could only install it through conda channel pytorch3d. However, it might cause a failure due to installed from different channel.
> > BTW, I would like to ask do you have the similar exception error,
> > An exception occurred in telemetry logging.Disabling telemetry to prevent further exceptions. Traceback (most recent call last): File "/home/miniconda38/envs/ove6d01/lib/python3.8/site-packages/iopath/common/file_io.py", line 946, in __log_tmetry_keys handler.log_event() File "/home/miniconda38/envs/ove6d01/lib/python3.8/site-packages/iopath/common/event_logger.py", line 97, in log_event del self._evt AttributeError: _evt
> 
> Sorry, I didn't have this failure issue as well as the exception error.

Thank you so much for your reply, do you mind to share what kind of environmental variable did you set to build pip install "git+https://github.com/facebookresearch/pytorch3d.git"

**Comment by dingdingcai** [comment]
> 



> > > > > Thank you for the work! I am trying to build with a conda environment but the i have some questions from the requirenments.txt.
> > > > > for pytorch3d, in the requirements.txt files # pytorch3d==0.4.0 in the pytorch3d github, the recommended pytorch version is PyTorch 1.4, 1.5.0, 1.5.1, 1.6.0, 1.7.0, or 1.7.1 however, the requirements.txt has pytorch 1.8.0 and torchvision=0.9.0
> > > > > any update on the requirenments.txt with a environment.yaml file will be great.
> > > > > Best
> > > > 
> > > > 
> > > > Hi, thank you for your interest! We installed Pytorch3d by the command "pip install "git+https://github.com/facebookresearch/pytorch3d.git" not the one "# pytorch3d==0.4.0" which is commented. The requirement.txt is updated by removing all commented lines.
> > > 
> > > 
> > > Thank you very much for the reply, I tried to install with the pip install "git+https://github.com/facebookresearch/pytorch3d.git" as well, but it failed. I could only install it through conda channel pytorch3d. However, it might cause a failure due to installed from different channel.
> > > BTW, I would like to ask do you have the similar exception error,
> > > An exception occurred in telemetry logging.Disabling telemetry to prevent further exceptions. Traceback (most recent call last): File "/home/miniconda38/envs/ove6d01/lib/python3.8/site-packages/iopath/common/file_io.py", line 946, in __log_tmetry_keys handler.log_event() File "/home/miniconda38/envs/ove6d01/lib/python3.8/site-packages/iopath/common/event_logger.py", line 97, in log_event del self._evt AttributeError: _evt
> > 
> > 
> > Sorry, I didn't have this failure issue as well as the exception error.
> 
> Thank you so much for your reply, do you mind to share what kind of environmental variable did you set to build pip install "git+https://github.com/facebookresearch/pytorch3d.git"

I installed python==3.8.5 with conda== 4.10.3
and  then run 
"pip install torch==1.8.0+cu111 torchvision==0.9.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html"
pip install "git+https://github.com/facebookresearch/pytorch3d.git"

Here is the log:
 ´´´
pip install torch==1.8.0+cu111 torchvision==0.9.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html
 ´´´
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Collecting torch==1.8.0+cu111
  Using cached https://download.pytorch.org/whl/cu111/torch-1.8.0%2Bcu111-cp38-cp38-linux_x86_64.whl (1982.2 MB)
Collecting torchvision==0.9.0+cu111
  Using cached https://download.pytorch.org/whl/cu111/torchvision-0.9.0%2Bcu111-cp38-cp38-linux_x86_64.whl (17.6 MB)
Requirement already satisfied: numpy in /home/dingding/miniconda3/lib/python3.8/site-packages (from torch==1.8.0+cu111) (1.19.2)
Collecting typing-extensions
  Downloading typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Requirement already satisfied: pillow>=4.1.1 in /home/dingding/miniconda3/lib/python3.8/site-packages (from torchvision==0.9.0+cu111) (8.1.2)
Installing collected packages: typing-extensions, torch, torchvision
Successfully installed torch-1.8.0+cu111 torchvision-0.9.0+cu111 typing-extensions-4.4.0

 ´´´
pip install "git+https://github.com/facebookresearch/pytorch3d.git"
 ´´´
Collecting git+https://github.com/facebookresearch/pytorch3d.git
  Cloning https://github.com/facebookresearch/pytorch3d.git to /tmp/pip-req-build-8oizby05
  Running command git clone -q https://github.com/facebookresearch/pytorch3d.git /tmp/pip-req-build-8oizby05
Requirement already satisfied: fvcore in /home/dingding/miniconda3/lib/python3.8/site-packages (from pytorch3d==0.7.1) (0.1.3.post20210317)
Requirement already satisfied: iopath in /home/dingding/miniconda3/lib/python3.8/site-packages (from pytorch3d==0.7.1) (0.1.6)
Requirement already satisfied: tqdm in /home/dingding/miniconda3/lib/python3.8/site-packages (from fvcore->pytorch3d==0.7.1) (4.59.0)
Requirement already satisfied: pyyaml>=5.1 in /home/dingding/miniconda3/lib/python3.8/site-packages (from fvcore->pytorch3d==0.7.1) (5.4.1)
Requirement already satisfied: termcolor>=1.1 in /home/dingding/miniconda3/lib/python3.8/site-packages (from fvcore->pytorch3d==0.7.1) (1.1.0)
Requirement already satisfied: yacs>=0.1.6 in /home/dingding/miniconda3/lib/python3.8/site-packages (from fvcore->pytorch3d==0.7.1) (0.1.8)
Requirement already satisfied: tabulate in /home/dingding/miniconda3/lib/python3.8/site-packages (from fvcore->pytorch3d==0.7.1) (0.8.9)
Requirement already satisfied: numpy in /home/dingding/miniconda3/lib/python3.8/site-packages (from fvcore->pytorch3d==0.7.1) (1.19.2)
Requirement already satisfied: Pillow in /home/dingding/miniconda3/lib/python3.8/site-packages (from fvcore->pytorch3d==0.7.1) (8.1.2)
Requirement already satisfied: portalocker in /home/dingding/miniconda3/lib/python3.8/site-packages (from iopath->pytorch3d==0.7.1) (2.2.1)
Building wheels for collected packages: pytorch3d
  Building wheel for pytorch3d (setup.py) ... done
  Created wheel for pytorch3d: filename=pytorch3d-0.7.1-cp38-cp38-linux_x86_64.whl size=33619052 sha256=96942ad1b960b15dfc4108e930654b0a7e2c990b11e5403dd7cb91e7e0758470
  Stored in directory: /tmp/pip-ephem-wheel-cache-w4uy0nvq/wheels/5e/a7/7c/814c3888eaaecaaf0f533faeb3c6812d82274484be51f7441c
Successfully built pytorch3d
Installing collected packages: pytorch3d
Successfully installed pytorch3d-0.7.1
"
