### ISSUE TITLE
viewpoint codebook issue

### ISSUE THREAD

**Issue by lgq-gpu** [dingdingcai/OVE6D-pose#4]
Hello, I'm sorry to bother you, I'd like to know with sex which code can get the viewpoint codebook of obj mesh object? @dingdingcai

**Comment by dingdingcai** [comment]
Hi, the viewpoint sampling and encoding can be found here 
https://github.com/dingdingcai/OVE6D-pose/blob/497414281fb2253bbe9567c2d00640d972676c00/evaluation/utils.py#L208

and  https://github.com/dingdingcai/OVE6D-pose/blob/497414281fb2253bbe9567c2d00640d972676c00/evaluation/utils.py#L118

**Comment by lgq-gpu** [comment]
Thank you for your reply, I'll check it out

**Comment by lgq-gpu** [comment]
Hello, I would like to ask if the input mesh model must be normalized? @dingdingcai

**Comment by dingdingcai** [comment]
> Hello, I would like to ask if the input mesh model must be normalized? @dingdingcai

I didn't try it, but I think mesh normalization is not mandatory and you have to make sure that the rendered depth is consistent with its real observation.

**Comment by lgq-gpu** [comment]
I see. Thank you for your reply. It's very disturbing @dingdingcai
