### ISSUE TITLE
Quantitative evaluation

### ISSUE THREAD

**Issue by Guptajakala** [dingdingcai/OVE6D-pose#5]
Hi, thanks for the great work! From what I understand, the current code only saves the pose outputs in BOP format. But doesn't include the code for computing the ADD, ADDS, <0.1d accuracy percentage, as well as the AUC curves which were presented in the paper (table 2,3). Did I miss anything?
https://github.com/dingdingcai/OVE6D-pose/blob/497414281fb2253bbe9567c2d00640d972676c00/evaluation/LMO_RCNN_OVE6D_pipeline.py#L255

**Comment by dingdingcai** [comment]
> Hi, thanks for the great work! From what I understand, the current code only saves the pose outputs in BOP format. But doesn't include the code for computing the ADD, ADDS, <0.1d accuracy percentage, as well as the AUC curves which were presented in the paper (table 2,3). Did I miss anything?
> 
> https://github.com/dingdingcai/OVE6D-pose/blob/497414281fb2253bbe9567c2d00640d972676c00/evaluation/LMO_RCNN_OVE6D_pipeline.py#L255

Thanks for your interest! Actually, we didn't use the AUC metric in the paper, instead only the standard VSD and ADD(-S) metrics are used. The evaluation is based on the code repositories [sixd_toolkit](https://github.com/thodan/sixd_toolkit) and [bop_toolkit](https://github.com/thodan/bop_toolkit) which are not included in the current code.
