### ISSUE TITLE
Rendering on the fly and training time

### ISSUE THREAD

**Issue by Guptajakala** [dingdingcai/OVE6D-pose#7]
Hi, thanks for the great work!

I noticed you are rendering on the fly. Have you tried pre-rendering offline the triplets? I guess it will be significantly faster to train, but the poses are constant in each epoch and I'm wondering whether it hurts the performance.

**Comment by dingdingcai** [comment]
Hi,

Thanks for your interest in our work! 

We could speed up the training process by pre-rendering the training data offline. But we didn't try this strategy in our experiments, and we only trained this model once in a single Nvidia RTX 3090 GPU.

As you mentioned, we hope to dynamically sample the poses and generate training samples as diverse as possible on the fly.
Therefore, it may affect performance depending on the diversity of the pre-rendered samples. The online rendering is quite efficient in our case as we only render the depth map, no other scene properties (e.g., light, background, physics ...) are needed.
