### ISSUE TITLE
Depth image distance

### ISSUE THREAD

**Issue by Guptajakala** [dingdingcai/OVE6D-pose#8]
Hi, thanks for the great work!

When buildling the codebook, it's mentioned the depth images were rendered offline at a certain distance from the camera. During the inference time, is there any preprocessing to make sure the template depth images match the observed depth image? E.g. when the depth image at test time is much much closer to the camera, is there any processing to deal with that?

**Comment by dingdingcai** [comment]
Thanks for your interest in our work!

The (both the rendered and observed) depth images are normalized by subtracting the mean value and are centered at 0. During testing, you can also rescale the depth image to ensure it shares a similar scale as the rendered images based on the relative scale between the actual observed distance and the rendering distance.

**Comment by Guptajakala** [comment]
that makes a lot of sense, thank you!
